### ISSUE TITLE
Add static dir to module mounts

### ISSUE THREAD

**Issue by mdehollander** [gethyas/create-hyas#8]
## Description

Files stored in the static dir are not included in the hugo build. For example the favicons are not found.

### Steps to reproduce

Run the create hyas project and see if the favicon are found in the logs.

### Expected result

The files in the static dir should be added to the public directory

### Actual result

The static files are not included

**Comment by h-enk** [comment]
Tested with the new [create-hyas](https://github.com/gethyas/create-hyas) (v1.0.3): `template-bootstrap-starter-rec`, replaced favicons, no module mount for static, seems to be working/looks OK to me:

![Snag_9da53d](https://github.com/gethyas/create-hyas/assets/3902872/1a20c059-c606-43b2-bba7-df8a6ed50b0b)

**Comment by salim-b** [comment]
Files in `static/` work for me, too (with latest create-hyas). Thus I think this can be closed.

**Comment by h-enk** [comment]
Will close this issue for now then. Mattias, feel free to reopen if you think that's needed.

**Comment by salim-b** [comment]
From [relevant doc](https://gohugo.io/hugo-modules/configuration/#module-configuration-mounts):

> When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.

Since none of [Doks current mounts](https://github.com/gethyas/create-hyas/blob/main/template-doks/config/_default/module.toml) target `static`, we don't need to explicitly add

```toml
[[mounts]]
  source = "static"
  target = "static"
```

Hugo already adds that implicitly.

But I guess it wouldn't hurt to explicitly add the remaining default mounts to our config, it would probably be clearer for people unfamiliar with Hugo mounts.

Currently absent default mounts include:

```toml
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'static'
  target = 'static'
```

**Comment by salim-b** [comment]
> > But I guess it wouldn't hurt to explicitly add the remaining default mounts to our config, it would probably be clearer for people unfamiliar with Hugo mounts.
> 
> I certainly agree /let's do that.

here u go: https://github.com/gethyas/create-hyas/pull/12

**Comment by h-enk** [comment]
Merged: https://github.com/gethyas/create-hyas/pull/12
